### PR TITLE
Initial hw2 for Manav Vora (mkvora2)

### PR DESCRIPTION
**Pull request by Manavvora**

### CODE REVIEW

**Comment by rahil-makadia** [comment]
I'll review this repo for the hw2 code review

**Comment by rahil-makadia** [comment]
Hi Manav, here are a couple of comments/suggestions about your current repo:
- I really like how you created a separate neural network class that inherits from the pytorch-provided classes
- In the DQN method of your DQN class, there might be some redundant code in the ```if len(self.memory) > self.batch_size``` block. You might wanna see if there are any refactorings there that might help your code be more efficient. But if you're happy with the runtime, then there's no need to spend time on that

Otherwise, your result plots look really good. Great job!

**Comment by Manavvora** [comment]
Hi Rahil, thank you for your comments. I'll look into the `if` block that you mentioned and see if I can streamline the code there.

**Comment by Manavvora** [comment]
Hey Rahil, the `if` block doesn't affect the runtime much, so I'll keep it for now. But I'll write a more streamlined code next time keeping this in mind.

**Pull request merged**
